In [4]:
import requests
import pandas as pd
url = 'http://www.ufcstats.com/fight-details/14e53999507c76a7'
response = requests.get(url)
html_content = response.text

In [26]:
sections = soup.find_all('section', class_='b-fight-details__section js-fight-section')
for section in sections:
    if section.find('table', class_='b-fight-details__table js-fight-table'):
        fight_section = section
        break
else:
    fight_section = None

if fight_section:
    print("Fight section with table found.")
    # Continue with your extraction logic here
else:
    print("Fight section with the desired table not found.")

Fight section with table found.

In [33]:
table = fight_section.find('table', class_='b-fight-details__table js-fight-table')

In [66]:
headers = []
if table:
    header_row = table.find('thead').find_all('th')
    headers = [header.get_text(strip=True) for header in header_row]
    headers.insert(0, 'Round')
    print("Headers:", headers)
else:
    print("Table not found within the section.")

Headers: ['Round', 'Fighter', 'KD', 'Sig. str.', 'Sig. str. %', 'Total str.', 'Td %', 'Td %', 'Sub. att', 'Rev.', 'Ctrl']

In [67]:
if table:
    all_rows_data = []
    current_round = ''  # Variable to keep track of the current round

    # Find all the tbody elements to handle multiple sections within the table
    for tbody in table.find_all('tbody'):
        rows = tbody.find_all(['tr', 'th'])  # Include <th> tags in the search to find round headers
        for row in rows:
            # Check if the row is a round header
            if row.name == 'th':
                # Extract the round number from the header
                current_round = row.get_text(strip=True)
                continue  # Skip further processing for header rows
            
            cells = row.find_all('td')
            # Initialize lists to hold data for two fighters in the row, including the current round
            fighter_1_data = [current_round]
            fighter_2_data = [current_round]
            for cell in cells:
                # Extract texts from each <p> tag within the cell
                stats = [p.get_text(strip=True) for p in cell.find_all('p')]
                if len(stats) == 2:
                    fighter_1_data.append(stats[0])
                    fighter_2_data.append(stats[1])
                elif len(stats) == 1:  # Handling the case where there might be only one stat in a cell
                    fighter_1_data.append(stats[0])
                    fighter_2_data.append('')  # Append an empty string if no stat for the second fighter
                else:  # If no <p> tags or an unexpected number, append placeholders or handle accordingly
                    fighter_1_data.append('N/A')
                    fighter_2_data.append('N/A')
            
            # Append the processed data for both fighters to all_rows_data
            all_rows_data.append(fighter_1_data)
            all_rows_data.append(fighter_2_data)
    
    # Print each row's data for verification
    for row_data in all_rows_data:
        print(row_data)
else:
    print("No table found.")

['Round 1', 'Sean Strickland', '0', '34 of 75', '45%', '39 of 80', '0 of 0', '---', '0', '0', '0:00']
['Round 1', 'Dricus Du Plessis', '0', '18 of 51', '35%', '19 of 52', '2 of 3', '66%', '0', '0', '0:28']
['Round 2', 'Sean Strickland', '0', '22 of 62', '35%', '26 of 66', '0 of 0', '---', '0', '0', '0:00']
['Round 2', 'Dricus Du Plessis', '0', '26 of 60', '43%', '26 of 60', '1 of 1', '100%', '0', '0', '0:22']
['Round 3', 'Sean Strickland', '0', '31 of 87', '35%', '31 of 87', '0 of 0', '---', '0', '0', '0:00']
['Round 3', 'Dricus Du Plessis', '0', '29 of 84', '34%', '29 of 85', '0 of 0', '---', '0', '0', '0:00']
['Round 4', 'Sean Strickland', '0', '33 of 85', '38%', '34 of 87', '0 of 0', '---', '0', '0', '0:00']
['Round 4', 'Dricus Du Plessis', '0', '29 of 73', '39%', '31 of 75', '3 of 5', '60%', '0', '0', '1:18']
['Round 5', 'Sean Strickland', '0', '53 of 99', '53%', '53 of 99', '0 of 0', '---', '0', '0', '0:00']
['Round 5', 'Dricus Du Plessis', '0', '35 of 86', '40%', '35 of 86', '0 of 2', '0%', '0', '0', '0:00']

In [68]:
if table:
    for tbody in table.find_all('tbody'):
        rows = tbody.find_all('tr')
        for row in rows:
            # Assuming the first column contains fighter names with links
            fighter_links = row.find_all('td')[0].find_all('a')
            for link in fighter_links:
                print(f"Fighter Name: {link.text}, URL: {link['href']}")

Fighter Name: Sean Strickland , URL: http://www.ufcstats.com/fighter-details/0d8011111be000b2
Fighter Name: Dricus Du Plessis , URL: http://www.ufcstats.com/fighter-details/0d7b51c9d2649a6e
Fighter Name: Sean Strickland , URL: http://www.ufcstats.com/fighter-details/0d8011111be000b2
Fighter Name: Dricus Du Plessis , URL: http://www.ufcstats.com/fighter-details/0d7b51c9d2649a6e
Fighter Name: Sean Strickland , URL: http://www.ufcstats.com/fighter-details/0d8011111be000b2
Fighter Name: Dricus Du Plessis , URL: http://www.ufcstats.com/fighter-details/0d7b51c9d2649a6e
Fighter Name: Sean Strickland , URL: http://www.ufcstats.com/fighter-details/0d8011111be000b2
Fighter Name: Dricus Du Plessis , URL: http://www.ufcstats.com/fighter-details/0d7b51c9d2649a6e
Fighter Name: Sean Strickland , URL: http://www.ufcstats.com/fighter-details/0d8011111be000b2
Fighter Name: Dricus Du Plessis , URL: http://www.ufcstats.com/fighter-details/0d7b51c9d2649a6e

In [70]:

df_total_data_by_round = pd.DataFrame(all_rows_data, columns=headers)
df_total_data_by_round

# all_rows_data

,Round,Fighter,KD,Sig. str.,Sig. str. %,Total str.,Td %,Td %,Sub. att,Rev.,Ctrl
0,Round 1,Sean Strickland,0,34 of 75,45%,39 of 80,0 of 0,---,0,0,0:00
1,Round 1,Dricus Du Plessis,0,18 of 51,35%,19 of 52,2 of 3,66%,0,0,0:28
2,Round 2,Sean Strickland,0,22 of 62,35%,26 of 66,0 of 0,---,0,0,0:00
3,Round 2,Dricus Du Plessis,0,26 of 60,43%,26 of 60,1 of 1,100%,0,0,0:22
4,Round 3,Sean Strickland,0,31 of 87,35%,31 of 87,0 of 0,---,0,0,0:00
5,Round 3,Dricus Du Plessis,0,29 of 84,34%,29 of 85,0 of 0,---,0,0,0:00
6,Round 4,Sean Strickland,0,33 of 85,38%,34 of 87,0 of 0,---,0,0,0:00
7,Round 4,Dricus Du Plessis,0,29 of 73,39%,31 of 75,3 of 5,60%,0,0,1:18
8,Round 5,Sean Strickland,0,53 of 99,53%,53 of 99,0 of 0,---,0,0,0:00
9,Round 5,Dricus Du Plessis,0,35 of 86,40%,35 of 86,0 of 2,0%,0,0,0:00